import './globals.css'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
import SessionProvider from './components/sessionProvider'
import { getServerSession } from 'next-auth'

export const metadata = {
  title: 'Voyddfolio',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  const session = await getServerSession()
  return (
    <html lang="en" className="bg-jet-400 dark">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="icon" href="/V-oyddfolio.svg" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Fjalla+One&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&family=Space+Grotesk:wght@300..700&family=Teko:wght@300..700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,600;0,700;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className="font-mono overflow-x-hidden bg-gradient-to-b from-sky-300 to-gem-400">
        <SessionProvider session={session}>
          <Navbar />
          {children}
          <Footer />
        </SessionProvider>
      </body>
    </html>
  )
}
